### ISSUE TITLE
MongoDB cleanup

### ISSUE THREAD

**Issue by RaymiiOrg** [fzaninotto/uptime#116]
MongoDB filled up the entire disk of the server I run uptime on. I had to restore a backup of a few days earlier and change all check times. How do I clean up mongodb from uptime?

**Comment by dereckson** [comment]
8 checks, every 20 seconds: OpenShift small gear stopped to work this night, with a 503 issue, as there is no place remaining on the disk. MongoDB is at 705 MB.
