### ISSUE TITLE
Ignore self signed certificate

### ISSUE THREAD

**Issue by toxinu** [fzaninotto/uptime#134]
It could be nice to have a option like "Ignore self signed certificate".

Thank you!

**Comment by shaunwarman** [comment]
Any update on this?

**Comment by jeremyjhall** [comment]
I have struggled with this issue too and would love to see a resolution.
The http options I am using for my check:

> agent: "false,"
> requestCert: "true,"
> rejectUnauthorized: "false,"

The address:

> https://someserver.local:8443/login

**Comment by freighty** [comment]
```
rejectUnauthorized: false
requestCert: true
agent: false
```

This is the correct way to implement what fzaninotto added in 920eebf
