### ISSUE TITLE
Request Timeouts on Deployment on Amazon EC2 Small and xLarge

### ISSUE THREAD

**Issue by harrisonca** [fzaninotto/uptime#174]
Wonderful project here, I'm happy to start playing with and understanding.  Unfortunately,  I am having issues with scalability with just 100 checks on Amazon AWS EC2 instances.  The Mongo DB is running on  MongoLabs hosted DB.

Standard Amazon AMI Linux
Node 0.10.17
NPM 1.3.9

I started with a Small EC2 instances, loaded up the checks with 100 popular websites, but i see large amounts of Request Timeout errors:

20:33:47 www.twitter.com responded with error "Request Timeout"
20:33:47 www.blogspot.com responded with error "Request Timeout"
20:33:47 www.windows.com responded with error "Request Timeout"
20:33:47 www.aol.com responded with error "Request Timeout"
20:33:47 www.wikimedia.org went down Request Timeout
20:33:47 goo.ne.jp responded with error "Request Timeout"
20:33:47 www.craigslist.org responded with error "Request Timeout"
....

Out of the 100 sites, maybe 70 of them are consistently or intermittently fail when checked.  My settings are rather standard:

60 second checks
15 second timeouts

Other scalability tweaks I though of:
- ulimit -n increased to max
- http MaxSockets increased just in case
- xLarge EC2 instance used

None of these have a noticeable effect on the Request Timeout problems.  Any other tweaks or setup steps I am overlooking?

**Comment by grokys** [comment]
Having the same issue here.

**Comment by DivyaYash** [comment]
@emiliobool Am struggling with the email notification setup in uptime..I understand from your comments that you have the email notification setup..Can you please paste here your default.yaml file that has the email notification enabled? It will be really very helpful, thanks in advance!
