### ISSUE TITLE
Is the project still active?

### ISSUE THREAD

**Issue by phanan** [fzaninotto/uptime#300]
Hi guys, I've asked this question before [via Google Groups](https://groups.google.com/forum/#!topic/node-uptime/gk3xF4xX7Rw) and received no answers, so I guess I'm asking here again. 

The [last commit](https://github.com/fzaninotto/uptime/commit/d9cc96cc835b65577e9bc8c94625eb2706a1b923) was amost one year ago; we have 66 open issues and 33 PR's. The question is: Is the project still under active development? If it is, maybe some of the owners can resume the activity -- I see @fzaninotto is still very active on Github. If it's not, any of you guys can make an "official port" and we can contribute to it instead? 

I really love this software and would like to see it grows much more than this.

**Comment by brantje** [comment]
Yes it is: https://twitter.com/brantje/status/562741071445495809

**Comment by phanan** [comment]
Nice. The downtime is a bit long for this project though ;)

**Comment by brantje** [comment]
But indeed, maybe an 'port' can be a solution.
I just started with an fork, based on another fork, and i will cherry pick some good additions.
If fzaninotto comes back then i can send a PR with all the patches the community made
Also i add every plugin i can find, so searching for plugins won't be necessary anymore.
