### ISSUE TITLE
All checks down "and marked new" since the install

### ISSUE THREAD

**Issue by imadarchid** [fzaninotto/uptime#322]
Hi, 

I'm running uptime on Ubuntu 14.04 and the installation was normal (I followed the tutorial). The web interface is working, but whenever I add a check, it is marked as new and always down.

Any idea about how to solve the problem ?

Thanks,

(Sorry for my english)

**Comment by sbrandexed** [comment]
Is the monitor enabled?

**Comment by imadarchid** [comment]
@sbrandexed Sorry, I didn't close this issue. It was just a problem with MongoDB, but after the re-install it worked like a charm. Thanks anyway :)
