### ISSUE TITLE
Shows the URL is down with the "unable to verify the first certificate" message

### ISSUE THREAD

**Issue by DivyaYash** [fzaninotto/uptime#335]
Please let me know how to fix this issue? I have read other issues that states I need to put in below lines..but not sure in which file I have to set and at what line etc..

rejectUnauthorized: false,
requestCert: true,
agent: false

**Comment by DivyaYash** [comment]
Found it, thanks!

**Comment by avalkowsky** [comment]
Thanks for sharing that!
