### ISSUE TITLE
How to disable Mongoose logging.

### ISSUE THREAD

**Issue by msdevstep** [fzaninotto/uptime#76]
We are deploying Uptime to a cloud environment, and anything that gets logged to the console is getting saved to a file, and eventually our environment fills up completely and we have to redeploy to removed the log file. Is there a way to disable logging every single Mongoose call?

**Comment by adonisv79** [comment]
We are also running the environment in production and mongoose is happily logging everything
we have tried setting mongoose.set('debug', false);
it keeps logging and calls including parameters which are security risks.

intel:logger:DEBUG Logger (testlogger1) created 
  intel:logger:DEBUG Logger (testlogger2) created 
  mquery findOne +4m test_col { param1: 'test',
  param2: 'adonis' } { readPreference: 
   ReadPreference {
     _type: 'ReadPreference',
     mode: 'nearest',
     tags: undefined,
     options: undefined },
  fields: undefined }
